Dashboard: add a view that shows tests in order of number of failures
servo/intermittent-tracker pull request #16
Opened 2024-03-10 22:35 UTC by azharcodeit

**Context:**
 
This bug is about showing a simple view of the tests that flake the most. We don't need to show all tests, but maybe it would be good to show the top 100 tests and the number of times they had unexpected results.

**Solution:**

- Created an app route /flaky_tests for a view, which contains a table that shows Test Path and Number of Unexpected Results
- Added a new function called `flaky_tests` to retrieve the top 100 flaky tests from the database. This function calculates the total unexpected count for each test and sorts them in descending order. It then fetches additional information using the `issues_mixin` function and returns the results. This functionality enhances our ability to identify and prioritize flaky tests in the system.

<br class="Apple-interchange-newline"> 

- [x] This PR solves issue #15 
- [x] `python3 -m intermittent_tracker.tests` doesn't report any error

2024-03-12 07:21 UTC, mrobinson requested changes
Nice work. Please also test this with the data I uploaded to the original issue to make sure that performance and behavior are as you expected them.

2024-03-12 07:21 UTC, mrobinson commented on intermittent_tracker/dashboard.py
> +def flaky_tests(limit=100):
Can this be called something like `most_flaky`?

2024-03-12 07:21 UTC, mrobinson commented on intermittent_tracker/flask_server.py
> +@app.route('/flaky_tests')
I recommend `most-flaky` here as well.

2024-03-12 07:21 UTC, mrobinson commented on intermittent_tracker/flask_server.py
> +def flaky_tests():
It's great that you made the method in `dashboard.py` take a parameter for number of tests, but can you also allow passing a URL parameter here to control that as well?

2024-03-12 07:21 UTC, mrobinson commented on intermittent_tracker/templates/flaky_tests.html
> +    <title>Top 100 Flaky Tests</title>
This title would have to change to be a bit more generic. Perhaps it could be "Flakiest Tests".

2024-03-12 13:16 UTC, azharcodeit commented
Hey @mrobinson, thanks for reviewing my PR!

I've addressed the comments that you left. Also, I've updated the summary of this PR, which now includes new description and demo video using data that you provided in the issue.

Could you please take a loot at it one more time?

2024-03-13 10:55 UTC, mrobinson approved these changes
Nicely done!

2024-03-13 10:58 UTC, merged