dashboard
servo/intermittent-tracker pull request #5
Opened 2023-01-28 08:58 UTC by delan

2023-01-30 10:32 UTC, delan commented on schema/dashboard.1.sql
> +END;
this was fun to write, but doing logic in triggers is awkward, so i might convert this to python

2023-01-31 07:46 UTC, delan commented on schema/dashboard.1.sql
> +END;
done in e296a12309f68810cc3227787041ca1bfed536cf

2023-01-31 09:25 UTC, mrobinson approved these changes
This looks great!

2023-01-31 09:58 UTC, mrobinson requested changes
Oh, there is one small change that would be useful here. Could the `attempts` endpoint return a list of intermittents that it hasn't seen before from the set provided? This will allow the CI to print whether a flake is new or already known -- making it easier to detect if a change adds flakiness.

2023-01-31 11:27 UTC, delan commented
Thanks! POST response done in 7dc4c7a86beb7d09cafa60f25f26f85264fbeda4.

2023-01-31 11:54 UTC, mrobinson approved these changes
Great! Thank you.

2023-01-31 12:09 UTC, delan commented
Migration steps for #4 and #5 done in production. The service will fail to restart unless updated to include this patch, due to the lack of `token` in config.json.

2023-02-01 13:28 UTC, delan commented on schema/dashboard.1.sql
> +    , "subtest" TEXT
tests are identified by (path,subtest), but some tests are not subtests. the obvious representation for such tests would be (path,NULL), but sqlite makes the (legal) decision to allow (path,NULL) to effectively bypass

1. PRIMARY KEY constraints ([“Each row in a table with a primary key must have a unique combination of values in its primary key columns. For the purposes of determining the uniqueness of primary key values, NULL values are considered distinct from all other values, including other NULLs.”](https://sqlite.org/lang_createtable.html#the_primary_key))
2. UNIQUE constraints ([“For each UNIQUE constraint on the table, each row must contain a unique combination of values in the columns identified by the UNIQUE constraint. For the purposes of UNIQUE constraints, NULL values are considered distinct from all other values, including other NULLs.”](https://sqlite.org/lang_createtable.html#unique_constraints))
3. FOREIGN KEY constraints ([“The foreign key constraint is satisfied if for each row in the child table either one or more of the child key columns are NULL, or there exists a row in the parent table for which each parent key column contains a value equal to the value in its associated child key column.”](https://sqlite.org/foreignkeys.html#fk_basics))

i managed to solve this by converting (path,NULL) to (path,'') and (path,subtest) to (path,'='||subtest) between the application and the database, but this makes every insert and select a bug waiting to happen. tomorrow i’ll see if i can automate this conversion with a [generated column](https://sqlite.org/gencol.html) that gets used in constraints.

2023-02-01 13:31 UTC, delan commented on schema/dashboard.1.sql
> +    , "subtest" TEXT
i managed to solve this by converting (path,NULL) to (path,'') and (path,subtest) to (path,'='||subtest) between the application and the database (191a6de9203bea8e9eddc27f91f66947ce20f151), but this makes every insert and select a bug waiting to happen.

tomorrow i’ll see if i can automate this conversion with a [generated column](https://sqlite.org/gencol.html) that gets used in constraints.

2023-02-02 07:14 UTC, delan commented on schema/dashboard.1.sql
> +    , "subtest" TEXT
done in 929854f14d2081731d9a99d7cd70065644ed763a

2023-02-02 11:49 UTC, mrobinson approved these changes
This looks good to me!

2023-02-02 11:55 UTC, merged